services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecret
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Rome
      - WEBHOOK_URL=https://788d-103-129-16-33.ngrok-free.app/
      - TZ=Asia/Bangkok
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=90
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/home/node/.n8n/custom/n8n-nodes-romulus:ro

volumes:
  n8n_data:
